[alembic]
script_location = a2_migrations
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .
timezone = UTC

# URL is overridden at runtime from the POSTGRES_URL environment variable in a2_migrations/env.py
sqlalchemy.url = postgresql://wooprice:change-me@localhost:5432/wooprice_a2

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
