"""A2.3-R2 Transformation Rule Engine — reconciled schema

Revision ID: a2_002_r2
Revises: a2_001
Create Date: 2026-06-26

Supersedes the conflicting LOCAL (a2_002) and REMOTE (a2_002) implementations.
This revision merges: REMOTE's AST formula engine + 5 rule types + propose/propose_all API
with LOCAL's a2_ table prefix + proposal provenance table + execution trace table +
publish_version() immutability enforcement.

New entities:
  a2_pricing_rules            — rule definitions with priority and type (5 types)
  a2_pricing_rule_versions    — immutable versioned formula + required inputs + publish guard
  a2_price_proposals          — proposals generated by the rule engine (Numeric precision)
  a2_proposal_provenance      — full input provenance per proposal (reproducibility)
  a2_execution_traces         — step-by-step audit trace per proposal (explainability)

Migration is additive. No existing A2 tables or SQLite tables are modified.
Default production stack is unaffected.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a2_002_r2"
down_revision: Union[str, None] = "a2_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── a2_pricing_rules ──────────────────────────────────────────────────────
    op.create_table(
        "a2_pricing_rules",
        sa.Column("rule_id", sa.String(36), primary_key=True),
        sa.Column("rule_name", sa.String(256), nullable=False),
        sa.Column("rule_type", sa.String(64), nullable=False),
        sa.Column("priority", sa.Integer, nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rule_type IN ('cost_plus', 'fx_based', 'fee_based', 'formula', 'competition')",
            name="a2_pricing_rules_rule_type_check",
        ),
    )
    op.create_index("ix_a2_pricing_rules_priority", "a2_pricing_rules", ["priority"])
    op.create_index("ix_a2_pricing_rules_is_active", "a2_pricing_rules", ["is_active"])

    # ── a2_pricing_rule_versions ──────────────────────────────────────────────
    op.create_table(
        "a2_pricing_rule_versions",
        sa.Column("version_id", sa.String(36), primary_key=True),
        sa.Column(
            "rule_id",
            sa.String(36),
            sa.ForeignKey("a2_pricing_rules.rule_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer, nullable=False),
        sa.Column("formula", sa.String(1024), nullable=False),
        sa.Column("required_inputs_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("is_published", sa.Boolean, nullable=False, server_default="0"),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean, nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "rule_id", "version_number",
            name="uq_a2_pricing_rule_versions_rule_version",
        ),
    )
    op.create_index("ix_a2_pricing_rule_versions_rule_id", "a2_pricing_rule_versions", ["rule_id"])
    op.create_index("ix_a2_pricing_rule_versions_current", "a2_pricing_rule_versions", ["rule_id", "is_current"])
    op.create_index("ix_a2_pricing_rule_versions_published", "a2_pricing_rule_versions", ["is_published"])

    # ── a2_price_proposals ────────────────────────────────────────────────────
    op.create_table(
        "a2_price_proposals",
        sa.Column("proposal_id", sa.String(36), primary_key=True),
        sa.Column("canonical_product_id", sa.String(36), nullable=False),
        sa.Column("source_id", sa.String(128), nullable=False),
        sa.Column("snapshot_id", sa.String(36), nullable=False),
        sa.Column("rule_id", sa.String(36), nullable=False),
        sa.Column("rule_version_id", sa.String(36), nullable=False),
        sa.Column("rule_version_number", sa.Integer, nullable=False),
        sa.Column("proposed_price", sa.Numeric(14, 4), nullable=False),
        sa.Column("currency", sa.String(10), nullable=False),
        sa.Column("input_values_json", sa.Text, nullable=False),
        sa.Column("proposal_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_a2_price_proposals_product", "a2_price_proposals", ["canonical_product_id", "generated_at"])
    op.create_index("ix_a2_price_proposals_snapshot", "a2_price_proposals", ["snapshot_id"])
    op.create_index("ix_a2_price_proposals_rule", "a2_price_proposals", ["rule_id", "rule_version_id"])
    op.create_index("ix_a2_price_proposals_hash", "a2_price_proposals", ["proposal_hash"])

    # ── a2_proposal_provenance ────────────────────────────────────────────────
    op.create_table(
        "a2_proposal_provenance",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "proposal_id",
            sa.String(36),
            sa.ForeignKey("a2_price_proposals.proposal_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(36), nullable=False),
        sa.Column("rule_version_id", sa.String(36), nullable=False),
        sa.Column("rule_version_number", sa.Integer, nullable=False),
        sa.Column("source_id", sa.String(128), nullable=False),
        sa.Column("snapshot_id", sa.String(36), nullable=False),
        sa.Column("formula", sa.String(1024), nullable=False),
        sa.Column("input_values_json", sa.Text, nullable=False),
    )
    op.create_index("ix_a2_proposal_provenance_proposal_id", "a2_proposal_provenance", ["proposal_id"])
    op.create_index("ix_a2_proposal_provenance_rule_version", "a2_proposal_provenance", ["rule_version_id"])

    # ── a2_execution_traces ───────────────────────────────────────────────────
    op.create_table(
        "a2_execution_traces",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "proposal_id",
            sa.String(36),
            sa.ForeignKey("a2_price_proposals.proposal_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("step_order", sa.Integer, nullable=False),
        sa.Column("step_name", sa.String(100), nullable=False),
        sa.Column("step_input_json", sa.Text, nullable=False),
        sa.Column("step_output_json", sa.Text, nullable=False),
        sa.Column("step_formula", sa.String(1024), nullable=False),
    )
    op.create_index("ix_a2_execution_traces_proposal_id", "a2_execution_traces", ["proposal_id"])


def downgrade() -> None:
    op.drop_index("ix_a2_execution_traces_proposal_id", table_name="a2_execution_traces")
    op.drop_table("a2_execution_traces")

    op.drop_index("ix_a2_proposal_provenance_rule_version", table_name="a2_proposal_provenance")
    op.drop_index("ix_a2_proposal_provenance_proposal_id", table_name="a2_proposal_provenance")
    op.drop_table("a2_proposal_provenance")

    op.drop_index("ix_a2_price_proposals_hash", table_name="a2_price_proposals")
    op.drop_index("ix_a2_price_proposals_rule", table_name="a2_price_proposals")
    op.drop_index("ix_a2_price_proposals_snapshot", table_name="a2_price_proposals")
    op.drop_index("ix_a2_price_proposals_product", table_name="a2_price_proposals")
    op.drop_table("a2_price_proposals")

    op.drop_index("ix_a2_pricing_rule_versions_published", table_name="a2_pricing_rule_versions")
    op.drop_index("ix_a2_pricing_rule_versions_current", table_name="a2_pricing_rule_versions")
    op.drop_index("ix_a2_pricing_rule_versions_rule_id", table_name="a2_pricing_rule_versions")
    op.drop_table("a2_pricing_rule_versions")

    op.drop_index("ix_a2_pricing_rules_is_active", table_name="a2_pricing_rules")
    op.drop_index("ix_a2_pricing_rules_priority", table_name="a2_pricing_rules")
    op.drop_table("a2_pricing_rules")
