"""A2.3-R2 ORM models: PriceProposalRecord, ProposalProvenanceRecord, ExecutionTraceRecord.

Co-located to avoid circular FK reference issues. All three tables use the
a2_ prefix for namespace isolation. proposed_price uses Numeric(14, 4) for
financial precision (fixes TD-A2.3-001 from original LOCAL A2.3).
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..database import A2Base


class PriceProposalRecord(A2Base):
    """Persisted price proposal generated by the Rule Engine."""

    __tablename__ = "a2_price_proposals"

    proposal_id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    canonical_product_id: Mapped[str] = mapped_column(String(36), nullable=False)
    source_id: Mapped[str] = mapped_column(String(128), nullable=False)
    snapshot_id: Mapped[str] = mapped_column(String(36), nullable=False)
    rule_id: Mapped[str] = mapped_column(String(36), nullable=False)
    rule_version_id: Mapped[str] = mapped_column(String(36), nullable=False)
    rule_version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    proposed_price: Mapped[float] = mapped_column(Numeric(14, 4), nullable=False)
    currency: Mapped[str] = mapped_column(String(10), nullable=False)
    input_values_json: Mapped[str] = mapped_column(Text, nullable=False)
    proposal_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    provenance: Mapped[list[ProposalProvenanceRecord]] = relationship(
        "ProposalProvenanceRecord",
        back_populates="proposal",
        cascade="all, delete-orphan",
    )
    trace: Mapped[list[ExecutionTraceRecord]] = relationship(
        "ExecutionTraceRecord",
        back_populates="proposal",
        order_by="ExecutionTraceRecord.step_order",
        cascade="all, delete-orphan",
    )


class ProposalProvenanceRecord(A2Base):
    """
    Provenance record linking a price proposal to all its source inputs.

    Enables full reproducibility: given rule_version_id + formula +
    input_values_json, any proposal can be re-derived deterministically
    at any future time via evaluate_formula().
    """

    __tablename__ = "a2_proposal_provenance"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    proposal_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("a2_price_proposals.proposal_id", ondelete="CASCADE"),
        nullable=False,
    )
    rule_id: Mapped[str] = mapped_column(String(36), nullable=False)
    rule_version_id: Mapped[str] = mapped_column(String(36), nullable=False)
    rule_version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    source_id: Mapped[str] = mapped_column(String(128), nullable=False)
    snapshot_id: Mapped[str] = mapped_column(String(36), nullable=False)
    formula: Mapped[str] = mapped_column(String(1024), nullable=False)
    input_values_json: Mapped[str] = mapped_column(Text, nullable=False)

    proposal: Mapped[PriceProposalRecord] = relationship(
        "PriceProposalRecord", back_populates="provenance"
    )


class ExecutionTraceRecord(A2Base):
    """Step-by-step audit record of formula evaluation for a price proposal.

    Every step's name, inputs, output, and formula string is stored so any
    proposal can be fully explained without re-running the computation.
    """

    __tablename__ = "a2_execution_traces"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    proposal_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("a2_price_proposals.proposal_id", ondelete="CASCADE"),
        nullable=False,
    )
    step_order: Mapped[int] = mapped_column(Integer, nullable=False)
    step_name: Mapped[str] = mapped_column(String(100), nullable=False)
    step_input_json: Mapped[str] = mapped_column(Text, nullable=False)
    step_output_json: Mapped[str] = mapped_column(Text, nullable=False)
    step_formula: Mapped[str] = mapped_column(String(1024), nullable=False)

    proposal: Mapped[PriceProposalRecord] = relationship(
        "PriceProposalRecord", back_populates="trace"
    )
